/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\models\powerbook_180_laptop_computer.glb 
Author: Museum of Engineering and Technology, Krakow (https://sketchfab.com/mitkrakow)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/powerbook-180-laptop-computer-e8f3fca6a88045c598f836e75406b1e8
Title: PowerBook 180 laptop computer
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Computer(props) {
  const { nodes, materials } = useGLTF(
    "./models/powerbook_180_laptop_computer.glb"
  );
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 3.098]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.MIM_1595_laptop_0.geometry}
            material={materials.laptop}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={200}
          />
          <mesh
            geometry={nodes.MIM_1595_drukarka_drukarka_0.geometry}
            material={materials.drukarka}
            position={[-3.437, 2.954, -2.933]}
            rotation={[Math.PI, 0.902, 0]}
            scale={200}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("./models/powerbook_180_laptop_computer.glb");
