/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\models\robert_the_fat_rat.glb 
Author: bean(alwayshasbean) (https://sketchfab.com/alwayshasbean)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/robert-the-fat-rat-c3312a6ca28b4e7fadab06dc5902adca
Title: robert the fat rat
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Rat(props) {
  const { nodes, materials } = useGLTF("./models/robert_the_fat_rat.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            geometry={nodes.zck_w_snowballswep_rat1_0.geometry}
            material={materials.rat1}
          />
          <mesh
            geometry={nodes.zck_w_snowballswep_rat2_0.geometry}
            material={materials.rat2}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("./models/robert_the_fat_rat.glb");
